mytestkey=This value is from LOCAL properties file


stripe.api.key=sk_test_******

stripe.create.session.url=https://api.stripe.com/v1/checkout/sessions

stripe.webhook.endpoint-secret=whsec_***